-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e626cd57090d8df0be21e4df0f4e55cc3511d6ab
    hooks:
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.16.0
    hooks:
    -   id: yapf
